const express = require("express");
const swaggerJsDoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");
const { version } = require("../../package.json");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "🚀 Lab365 - Trinidade Places API",
      version: version,
      description: `Server resources documentation generated by <b>Ariel Duarte (c) 2023</b>.
        <a target="_blank" href="https://documenter.getpostman.com/view/3891670/2s93RRvsq2"> POSTMAN Documentation</a>
        <br />
        <h4><a target="_blank" href="https://github.com/reyduar/lab-365-trindade-places-api">API Repository</a></h4>
        `,
    },
    // components: {
    //   securitySchemas: {
    //     bearerAuth: {
    //       type: "t",
    //     },
    //   },
    // },
  },
  servers: [
    {
      url: "http://localhost:3333/api",
      description: "Development server",
    },
    {
      url: "https://trindade-places-api.cyclic.app/api/",
      description: "Production server",
    },
  ],
  apis: ["./src/routes/*.js", "./src/models/*.js"],
};

const swaggerSpec = swaggerJsDoc(options);

const swaggerDocs = (app, port) => {
  // Swagger page
  app.use("/api/docs", swaggerUi.serve);
  app.use("/api/docs", swaggerUi.setup(swaggerSpec));

  // Docs in JSON format
  app.get("/api/docs.json", (req, res) => {
    res.setHeader("Content-Type", "application/json");
    res.send(swaggerSpec);
  });
  console.log(
    `Docs available at https://trindade-places-api.cyclic.app/api/docs`
  );
};

module.exports = {
  swaggerDocs,
};
